Include(FindSDL)
Include(FindFreetype)
Include(FindZLIB)
Find_Package(SDL REQUIRED)
Find_Package(Freetype REQUIRED)
Find_Package(ZLIB REQUIRED)
Find_Package(PNG)
if (PNG_FOUND)
    list(APPEND SCUMMVM_LIBRARIES ${PNG_LIBRARIES})
    list(APPEND SCUMMVM_DEFINES -DUSE_PNG)
endif()

#Find_Package(VORBIS)
if (VORBIS_FOUND)
    list(APPEND SCUMMVM_LIBRARIES ${VORBIS_LIBRARIES})
    list(APPEND SCUMMVM_DEFINES -DUSE_VORBIS)
endif()
